### ISSUE TITLE
what is the license of beaudiomer.py?

### ISSUE THREAD

**Issue by bremner** [kisonecat/beaudiomer#1]
I'm thinking about packing beaudiomer and autocut for Debian, so I need to be clear about the licenses.
I notice autocut is GPL3; that would be fine. I imaging lppl would also be OK, although I haven't looked at how it would apply to a python script.

**Comment by kisonecat** [comment]
Thank you for pointing this out, and it would be so great to get this packaged for Debian.

The commit fb408b7d62f164d1a358d9177216cd1eaab33c93 should fix this, licensing beaudiomer just as beamer is licensed, i.e., under both the GPL and the LPPL.
